import { apiSlice } from "./apiSlice";

// ─────────────────────────────────────────────────────────────────────────────
// Types — mirror FastAPI notification_schema.py exactly
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Notification types generated by the backend task workflow:
 *   TASK_ASSIGNED    — sent to employee when a task is created for them
 *   TASK_SUBMITTED   — sent to manager when employee submits a task
 *   TASK_RESUBMITTED — sent to manager when employee resubmits a rejected task
 *   TASK_APPROVED    — sent to employee when manager approves their task
 *   TASK_REJECTED    — sent to employee when manager rejects their task
 */
export type NotificationType =
  | "TASK_ASSIGNED"
  | "TASK_SUBMITTED"
  | "TASK_RESUBMITTED"
  | "TASK_APPROVED"
  | "TASK_REJECTED";

/**
 * NotificationResponse — matches FastAPI NotificationResponse schema exactly.
 *
 * id         : number
 * user_id    : number   — the recipient
 * task_id    : number | null — the related task (may be null)
 * type       : NotificationType string
 * title      : string
 * message    : string
 * is_read    : boolean  — false until PATCH /{id}/read is called
 * created_at : ISO 8601 datetime string
 * read_at    : ISO 8601 datetime string | null — set when marked read
 */
export interface NotificationResponse {
  id: number;
  user_id: number;
  task_id: number | null;
  type: string;             // NotificationType — kept as string for forward-compat
  title: string;
  message: string;
  is_read: boolean;
  created_at: string;       // ISO 8601
  read_at: string | null;   // ISO 8601 or null
}

// ─────────────────────────────────────────────────────────────────────────────
// RTK Query endpoints — injected into the central apiSlice
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Notification API endpoints.
 *
 * GET   /notifications            → list[NotificationResponse]
 *   Returns all notifications for the authenticated user, newest first.
 *   Scoped to the current user — no role filtering needed.
 *
 * GET   /notifications/{id}       → NotificationResponse
 *   Returns a single notification owned by the current user.
 *   Returns 404 if not found or not owned by current user.
 *
 * PATCH /notifications/{id}/read  → NotificationResponse
 *   Marks a notification as read. Sets is_read=true, read_at=now.
 *   No request body required.
 *   Returns the updated NotificationResponse.
 *
 * NOTE: There is NO bulk mark-all-read endpoint in the backend.
 *       Each notification must be marked read individually.
 */
export const notificationApi = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    // ── GET /notifications ────────────────────────────────────────────────
    getNotifications: builder.query<NotificationResponse[], void>({
      query: () => "/notifications",
      providesTags: (result) =>
        result
          ? [
              ...result.map(({ id }) => ({
                type: "Notifications" as const,
                id,
              })),
              { type: "Notifications", id: "LIST" },
            ]
          : [{ type: "Notifications", id: "LIST" }],
    }),

    // ── GET /notifications/{id} ───────────────────────────────────────────
    getNotification: builder.query<NotificationResponse, number>({
      query: (id) => `/notifications/${id}`,
      providesTags: (_result, _err, id) => [{ type: "Notifications", id }],
    }),

    // ── PATCH /notifications/{id}/read ────────────────────────────────────
    /**
     * Marks a single notification as read.
     * No request body — the backend uses the current user's identity from
     * the Bearer token to verify ownership before marking read.
     * Invalidates the specific notification AND the list so the unread
     * count in the Header badge refreshes automatically.
     */
    markNotificationRead: builder.mutation<NotificationResponse, number>({
      query: (id) => ({
        url: `/notifications/${id}/read`,
        method: "PATCH",
      }),
      invalidatesTags: (_result, _err, id) => [
        { type: "Notifications", id },
        { type: "Notifications", id: "LIST" },
      ],
    }),
  }),
  overrideExisting: false,
});

export const {
  useGetNotificationsQuery,
  useGetNotificationQuery,
  useMarkNotificationReadMutation,
} = notificationApi;
